/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.HomePage;


import Professor.ProfessorCourses;
import Professor.ProfessorHistory;
import Professor.ProfessorProfile;
import Student.Studentde;
import java.awt.CardLayout;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shush
 */
public class ProfessorHomePageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorHomePageJPanel
     */
    Professor.ProfessorHistory history;
    private JPanel userProcessContainer;
    private Professor.ProfessorHistory ph;
    ProfessorProfile p;
    private String profid;
    public ProfessorHomePageJPanel(JPanel userProcessContainer,ProfessorHistory ph,String neuid,ProfessorHistory history  ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ph = ph;
        this.profid = neuid;
        this.history = history;
        p = ph.SearchProfessorbyneuid(neuid);
        for(ProfessorCourses p : ph.getProfessor_courselist()){
            System.out.println(p.getProf_name() + " " + p.getProf_id());
            for(Courses.CourseDetails c: p.getCourselists()){
                System.out.println(c.getCoursename());
            }
                
            
        }
        Professor.ProfessorProfile p = ph.SearchProfessorbyneuid(neuid);
        txtName.setText(p.getProf_first_name() + " " + p.getProf_last_name());
        txtProf_Speciality.setText(p.getProf_speciality());
        populatetable();
//        String imagePathValue = "Speakerseries_costco.png";
        ImageIcon ii = new ImageIcon(getClass().getResource("/UI_Images/Faculty1.jpeg.jpg"));
        Image image = ii.getImage();
        int width = 50; // Set the desired width
        int height = 50;
        Image scaledImage = image.getScaledInstance(width, height, Image.SCALE_DEFAULT);
        ImageIcon scaledImageIcon = new ImageIcon(scaledImage);
        txtProfile.setIcon(new ImageIcon(image));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbProfessorList = new javax.swing.JTable();
        StudentInformationBtn = new javax.swing.JButton();
        SettingsBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtProfile = new javax.swing.JLabel();
        lbLname = new javax.swing.JLabel();
        lbFname = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        txtProf_Speciality = new javax.swing.JLabel();
        RefershCourseListBtn = new javax.swing.JButton();
        AddCoursesBtn = new javax.swing.JButton();
        PaymentBtn = new javax.swing.JButton();

        tbProfessorList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course Name", "Course CRN", "Course Term", "Course Type"
            }
        ));
        jScrollPane1.setViewportView(tbProfessorList);

        StudentInformationBtn.setBackground(new java.awt.Color(0, 51, 51));
        StudentInformationBtn.setForeground(new java.awt.Color(255, 255, 255));
        StudentInformationBtn.setText("Student Information");
        StudentInformationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentInformationBtnActionPerformed(evt);
            }
        });

        SettingsBtn.setBackground(new java.awt.Color(0, 51, 51));
        SettingsBtn.setForeground(new java.awt.Color(255, 255, 255));
        SettingsBtn.setText("Settings");
        SettingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsBtnActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Professor DashBoard");

        lbLname.setText("Specialization:");

        lbFname.setText("Name:");

        RefershCourseListBtn.setText("Refresh Table");
        RefershCourseListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefershCourseListBtnActionPerformed(evt);
            }
        });

        AddCoursesBtn.setBackground(new java.awt.Color(0, 51, 51));
        AddCoursesBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddCoursesBtn.setText("Add Courses");
        AddCoursesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCoursesBtnActionPerformed(evt);
            }
        });

        PaymentBtn.setBackground(new java.awt.Color(0, 51, 51));
        PaymentBtn.setForeground(new java.awt.Color(255, 255, 255));
        PaymentBtn.setText("Payment Method");
        PaymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(AddCoursesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(328, 328, 328)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SettingsBtn)
                                    .addComponent(StudentInformationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PaymentBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lbLname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbFname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(13, 13, 13)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtProf_Speciality, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(RefershCourseListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbFname)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbLname)
                            .addComponent(txtProf_Speciality, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(RefershCourseListBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(AddCoursesBtn)
                        .addGap(18, 18, 18)
                        .addComponent(StudentInformationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PaymentBtn)
                        .addGap(60, 60, 60)
                        .addComponent(SettingsBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void StudentInformationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentInformationBtnActionPerformed
        // TODO add your handling code here:
        UserInterface.SignupPage.Professor.StudentGradingJPanel panel = new UserInterface.SignupPage.Professor.StudentGradingJPanel(userProcessContainer,ph,profid,history);
        userProcessContainer.add("StudentGradingJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_StudentInformationBtnActionPerformed

    private void RefershCourseListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefershCourseListBtnActionPerformed
        // TODO add your handling code here:
         DefaultTableModel dtm = (DefaultTableModel) tbProfessorList.getModel();
        dtm.setRowCount(0);
        ProfessorCourses pc = ph.SearchProfessorCoursesbyneuid(profid);
        for(Courses.CourseDetails c : pc.getCourselists()){
            Object[] row = new Object[4];
            row[0] = c.getCoursename();
            row[1] = c.getCRN();
            row[2] = c.getTerm_offered();
            row[3] = c.getCourse_Type();
            
            dtm.addRow(row);
        }
//       
    }//GEN-LAST:event_RefershCourseListBtnActionPerformed

    private void AddCoursesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCoursesBtnActionPerformed
        // TODO add your handling code here:
        
        UserInterface.ProfessorCourseCreationJPanel panel = new UserInterface.ProfessorCourseCreationJPanel(userProcessContainer,ph,profid);
        userProcessContainer.add("ProfessorCourseCreationJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_AddCoursesBtnActionPerformed

    private void PaymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaymentBtnActionPerformed

    private void SettingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsBtnActionPerformed
        // TODO add your handling code here:
        UserInterface.ContentUpdate.ProfessorDetailUpdateJPanel panel = new UserInterface.ContentUpdate.ProfessorDetailUpdateJPanel(userProcessContainer,ph,p);
        userProcessContainer.add("ProfessorDetailUpdateJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_SettingsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCoursesBtn;
    private javax.swing.JButton PaymentBtn;
    private javax.swing.JButton RefershCourseListBtn;
    private javax.swing.JButton SettingsBtn;
    private javax.swing.JButton StudentInformationBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbFname;
    private javax.swing.JLabel lbLname;
    private javax.swing.JTable tbProfessorList;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtProf_Speciality;
    private javax.swing.JLabel txtProfile;
    // End of variables declaration//GEN-END:variables

    private void populatetable() {
        DefaultTableModel dtm = (DefaultTableModel) tbProfessorList.getModel();
        dtm.setRowCount(0);
        ProfessorCourses pc = ph.SearchProfessorCoursesbyneuid(profid);
        for(Courses.CourseDetails c : pc.getCourselists()){
            Object[] row = new Object[4];
            row[0] = c.getCoursename();
            row[1] = c.getCRN();
            row[2] = c.getTerm_offered();
            row[3] = c.getCourse_Type();
            
            dtm.addRow(row);
        }
//       
    }
    
}
