/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.SignupPage;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.awt.CardLayout;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Professor.ProfessorHistory;
import Student.Studentde;
import UserInterface.HomePage.ProfessorHomePageJPanel;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author devmi
 */
public class Studentsignup extends javax.swing.JPanel {

        private JPanel userProcessContainer;
     Professor.ProfessorHistory history;
         Professor.ProfessorHistory coursehistory;
         Professor.ProfessorHistory regcoursehistory;
          Professor.ProfessorHistory sugg;
    /**
     * Creates new form Studentsignup
     */
    public Studentsignup(JPanel userProcessContainer, ProfessorHistory history, ProfessorHistory coursehistory, ProfessorHistory regcoursehistory,  ProfessorHistory sugg){ 
        
         initComponents();
        this.history = history;
        this.coursehistory = coursehistory;
        this.regcoursehistory = regcoursehistory;
        this.sugg = sugg;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewuserjpanel1 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        txtneu = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        SSN3 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        Role = new javax.swing.JLabel();
        txt = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtphonenumber = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        txtdepartment = new javax.swing.JTextField();
        txtacceptedyear = new javax.swing.JTextField();
        txtgraduatedyear = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtcampus = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        viewuserjpanel1.setBackground(new java.awt.Color(211, 242, 242));
        viewuserjpanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setText("NEU-ID");
        viewuserjpanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 130, 20));
        viewuserjpanel1.add(txtneu, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 290, -1));

        jLabel42.setText(" Name");
        viewuserjpanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 105, -1));

        SSN3.setText("Phone Number");
        viewuserjpanel1.add(SSN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 105, 20));

        jLabel45.setText("Age");
        viewuserjpanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 105, -1));

        Role.setText("Email -Id");
        viewuserjpanel1.add(Role, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 105, -1));
        viewuserjpanel1.add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 289, -1));
        viewuserjpanel1.add(txtage, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 289, -1));

        txtphonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphonenumberActionPerformed(evt);
            }
        });
        viewuserjpanel1.add(txtphonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 289, -1));
        viewuserjpanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 289, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Student Sign up");
        viewuserjpanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 890, 70));

        jLabel6.setText("Password");
        viewuserjpanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 60, -1));
        viewuserjpanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 290, -1));
        viewuserjpanel1.add(txtdepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 290, -1));
        viewuserjpanel1.add(txtacceptedyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 290, -1));
        viewuserjpanel1.add(txtgraduatedyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, 290, -1));

        jLabel8.setText("Department");
        viewuserjpanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 80, -1));

        jLabel9.setText("Accepted Year");
        viewuserjpanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 80, -1));

        jLabel10.setText("Expected Graduation Year");
        viewuserjpanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, -1, -1));

        jLabel13.setText("Campus");
        viewuserjpanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));
        viewuserjpanel1.add(txtcampus, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 290, -1));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        viewuserjpanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 610, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 921, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(viewuserjpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewuserjpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtphonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphonenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphonenumberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
  boolean duplicatePerson = false;

    for (Student.Studentde psc : history.getHistory()) {
        if (psc.getNEUID().equals(txtneu.getText())) {
            duplicatePerson = true;
            break;
        }
    }

    if (!duplicatePerson) {
 String Name = txt.getText();
        String Department = txtdepartment.getText();
        String Campus = txtcampus.getText();
        String email = txtemail.getText();
        int Age = Integer.parseInt(txtage.getText());
        int  phoneno= Integer.parseInt(txtphonenumber.getText());
        String Acceptedyear = txtacceptedyear.getText();
        String Gradyear = txtgraduatedyear.getText();
        String Password = txtpassword.getText();
        String NEUID = txtneu.getText();
        Student.Studentde psc = history.addnuser();

        
        
        psc.setName(Name);
        psc.setCampus(Campus);
        psc.setNEUID(NEUID);
        psc.setAge(Age);
        psc.setGradyear(Gradyear);
        psc.setPhoneno(phoneno);
        psc.setEmail_Id(email);
        psc.setAcceptedyear(Acceptedyear);
        psc.setPassword(Password);
        psc.setSpecalization(Department);
        
        
        
        txt.setText("");
        txtdepartment.setText("");
        txtcampus.setText("");
        txtemail.setText("");
        txtage.setText("");
        txtphonenumber.setText("");
        txtacceptedyear.setText("");
        txtgraduatedyear.setText("");
        txtpassword.setText("");
        txtneu.setText("");        JOptionPane.showMessageDialog(this, "New Person is added");
    } else {
        JOptionPane.showMessageDialog(this, "NEUID has been used by another Student. Enter a new one.");
    }
    }//GEN-LAST:event_jButton1ActionPerformed


     private void addtheperson()
    {
       
      
        
        
        
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Role;
    private javax.swing.JLabel SSN3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt;
    private javax.swing.JTextField txtacceptedyear;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtcampus;
    private javax.swing.JTextField txtdepartment;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtgraduatedyear;
    private javax.swing.JTextField txtneu;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtphonenumber;
    private javax.swing.JPanel viewuserjpanel1;
    // End of variables declaration//GEN-END:variables
}
