/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.LoginPage;

/**
 *
 * @author devmi
 */
import Professor.ProfessorHistory;
import Student.Studentde;
import UserInterface.HomePage.ProfessorHomePageJPanel;
import java.awt.CardLayout;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
public class AdminloginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminloginJPanel
     */
    Professor.ProfessorHistory ph;
     Employer.EmployerHistory eh;
    Professor.ProfessorHistory history;
        Professor.ProfessorHistory coursehistory;
        Professor.ProfessorHistory regcoursehistory;
         Professor.ProfessorHistory sugg;
         Professor.ProfessorHistory addlog;
         JPanel userProcessContainer;
         String p_neuid;
    public AdminloginJPanel(JPanel userProcessContainer,ProfessorHistory addlog ,ProfessorHistory history,ProfessorHistory ph, String p_neuid,ProfessorHistory coursehistory,ProfessorHistory regcoursehistory, ProfessorHistory sugg) {
     initComponents();
        this.userProcessContainer = userProcessContainer;
        this.regcoursehistory = regcoursehistory;
        this.history = history;
        this.coursehistory = coursehistory;
        this.sugg = sugg;
        this.ph = ph;
        this.p_neuid = p_neuid; 
    this.addlog = addlog;
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LoginBtn = new javax.swing.JButton();
        txtpassa = new javax.swing.JTextField();
        txtneuida = new javax.swing.JTextField();
        lbFname = new javax.swing.JLabel();
        lbLname = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrator Login");

        LoginBtn.setText("Login");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        txtneuida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtneuidaActionPerformed(evt);
            }
        });

        lbFname.setText("Userid");

        lbLname.setText("Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbLname, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbFname))
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoginBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtneuida)
                                .addComponent(txtpassa, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtneuida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpassa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLname))
                .addGap(34, 34, 34)
                .addComponent(LoginBtn)
                .addContainerGap(295, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
        int n=0;
        String p_neuida = txtneuida.getText();
        String p_password = txtpassa.getText();
        System.out.println(p_neuid);
        for (Student.Adminlog p : addlog.getAddlog())
        {
            System.out.println(p.getUsername());
            if(p.getUsername().equals(p_neuida) && p.getPassword().equals(p_password))
            {
                //         //        UserInterface.LoginPage.StudentLoginJPanel panel = new UserInterface.LoginPage.StudentLoginJPanel(userProcessContainer, history,ph, neuid, coursehistory,regcoursehistory, sugg);

                JOptionPane.showMessageDialog(this,"Access Granted");
                UserInterface.Thirdparty.test panel = new UserInterface.Thirdparty.test(userProcessContainer,history,ph,p_neuid,coursehistory,regcoursehistory,sugg);
                userProcessContainer.add("test", panel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
                n++;
                //Studenth(JPanel userProcessContainer, ProfessorHistory history, ProfessorHistory ph, String p_neuid, ProfessorHistory coursehistory, ProfessorHistory regcoursehistory,  ProfessorHistory sugg) {
                }
            }

            if(n==0)
            {
                JOptionPane.showMessageDialog(this,"Access Denied");
                n=0;
            }
            txtneuida.setText("");
            txtpassa.setText("");

    }//GEN-LAST:event_LoginBtnActionPerformed

    private void txtneuidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtneuidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtneuidaActionPerformed

    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbFname;
    private javax.swing.JLabel lbLname;
    private javax.swing.JTextField txtneuida;
    private javax.swing.JTextField txtpassa;
    // End of variables declaration//GEN-END:variables
}
