/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.LoginPage;

import Employer.JobRoles;
import Professor.ProfessorHistory;
import java.awt.CardLayout;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



/**
 *
 * @author shush
 */
public class EmployerLoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EmployerLoginJPanel
     */
    Professor.ProfessorHistory coursehistory;
    Professor.ProfessorHistory regcoursehistory;
    private JPanel userProcessContainer;
    private Professor.ProfessorHistory ph;
    private Employer.EmployerHistory eh;
    public EmployerLoginJPanel(JPanel userProcessContainer, ProfessorHistory ph, Employer.EmployerHistory eh,ProfessorHistory coursehistory,ProfessorHistory regcoursehistory){
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ph = ph;
        this.eh = eh;
        this.regcoursehistory = regcoursehistory;
        this.coursehistory = coursehistory;
        for(Employer.EmployerJobRoles empjroles: eh.getEmployerhistory()){
            System.out.println(empjroles.getEmployer_name());
            for(JobRoles j:empjroles.getEmp_rolelists()){
                System.out.println(j.getRole_name());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPassword = new javax.swing.JTextField();
        LoginBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SignupBtn = new javax.swing.JButton();
        ResetPasswordBtn = new javax.swing.JButton();
        lbLname = new javax.swing.JLabel();
        lbFname = new javax.swing.JLabel();
        txtemployerid = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 157, 185, -1));

        LoginBtn.setText("Login");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 207, 80, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employer Login");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 10, 860, 70));

        SignupBtn.setText("Signup");
        SignupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupBtnActionPerformed(evt);
            }
        });
        add(SignupBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 316, 82, -1));

        ResetPasswordBtn.setText("Reset Password?");
        ResetPasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetPasswordBtnActionPerformed(evt);
            }
        });
        add(ResetPasswordBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 207, -1, -1));

        lbLname.setText("Password:");
        add(lbLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 157, 84, -1));

        lbFname.setText("Employer id:");
        add(lbFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 123, -1, -1));

        txtemployerid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemployeridActionPerformed(evt);
            }
        });
        add(txtemployerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 117, 185, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
        String empid = txtemployerid.getText();
        String prof_password = txtPassword.getText();
        Employer.EmployerProfile e = eh.SearchEmployerProfilebyid(empid);
        if(e==null){
            JOptionPane.showMessageDialog(this,"Access Denied");
        }
        else{
            if(e.getEmployer_password().equals(prof_password)){
                JOptionPane.showMessageDialog(this,"Access Granted");
            }
            else{
                JOptionPane.showMessageDialog(this,"Incorrect password!! Please Try again");
            }
        }
        txtemployerid.setText("");
        txtPassword.setText("");
        UserInterface.HomePage.EmployerHomepageJPanel panel = new UserInterface.HomePage.EmployerHomepageJPanel(userProcessContainer,ph,eh,empid,coursehistory,regcoursehistory);
        userProcessContainer.add("ProfessorHomePageJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void SignupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupBtnActionPerformed
        // TODO add your handling code here:
        UserInterface.SignupPage.EmployerSignupJPanel panel = new UserInterface.SignupPage.EmployerSignupJPanel(userProcessContainer,ph,eh);
        userProcessContainer.add("EmployerSignupJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_SignupBtnActionPerformed

    private void ResetPasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetPasswordBtnActionPerformed
        // TODO add your handling code here:
        UserInterface.ResetPassword.EmployerResetPasswordJPanel panel = new UserInterface.ResetPassword.EmployerResetPasswordJPanel(userProcessContainer,ph,eh,coursehistory,regcoursehistory);
        userProcessContainer.add("EmployerResetPasswordJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_ResetPasswordBtnActionPerformed

    private void txtemployeridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemployeridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemployeridActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBtn;
    private javax.swing.JButton ResetPasswordBtn;
    private javax.swing.JButton SignupBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbFname;
    private javax.swing.JLabel lbLname;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtemployerid;
    // End of variables declaration//GEN-END:variables




}
