/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface;

import Professor.ProfessorCourses;
import Professor.ProfessorHistory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shush
 */
public class ProfessorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorJPanel
     */
    private JPanel userProcessContainer;
    private Professor.ProfessorCourses pd;
    private Professor.ProfessorHistory ph;
    private Courses.CourseCreation cc;
    public ProfessorJPanel(JPanel userProcessContainer, ProfessorHistory ph, Courses.CourseCreation cc,ProfessorCourses pd) {
         initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ph = ph;
        this.cc = cc;
        this.pd = pd;
        populateTable();
    }
    private void populateTable() {
//        DefaultTableModel dtm = (DefaultTableModel) tbProfessorList.getModel();
//        dtm.setRowCount(0);
//        for(Professor.ProfessorProfile p: pd.getProfessorlists()) {
//            Object[] row = new Object[5];
//            row[0] = p.getProf_id();
//            row[1] = p.getProf_first_name();
//            row[2] = p.getProf_speciality();
//            row[3] = p.getProf_experience();
//            row[4] = p.getProf_resident();
//            
//            dtm.addRow(row);
//        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbProfessorList = new javax.swing.JTable();
        BackBtn = new javax.swing.JButton();
        Prof_Courses = new javax.swing.JButton();

        tbProfessorList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Professor id", "Professor name", "speciality", "experience", "Country"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbProfessorList);

        BackBtn.setText("<<Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        Prof_Courses.setText("Professor Courses");
        Prof_Courses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Prof_CoursesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(Prof_Courses)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(BackBtn)
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(Prof_Courses)
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void Prof_CoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Prof_CoursesActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tbProfessorList.getSelectedRow();
          if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this,"Please Select a row to view");
            return;
        }
//        DefaultTableModel model = (DefaultTableModel) tbProfessorList.getModel();
//        Professor.ProfessorProfile professor_select = (ProfessorProfile)model.getValueAt(selectedRowIndex, 0);
          
    }//GEN-LAST:event_Prof_CoursesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton Prof_Courses;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbProfessorList;
    // End of variables declaration//GEN-END:variables
}
