/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Courses.CourseDetails;
import java.awt.CardLayout;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Employer.EmployerHistory;
import Professor.ProfessorHistory;
import Student.Studentde;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.text.SimpleDateFormat;

/**
 *
 * @author devmi
 */
public class professorcview extends javax.swing.JPanel {
    private JPanel userProcessContainer;
     Professor.ProfessorHistory history;
         Professor.ProfessorHistory coursehistory;
         Professor.ProfessorHistory regcoursehistory;
          Professor.ProfessorHistory sugg;
                   
    String CRN;
    String Subject_code;
    String Term_offered;
    String professor_name;
    String Subject;
    String pre_requisite;
    String Department;
    String startDateTime;
    String endDateTime;
    String Description;
    int Credits;
    String status;
    String mode;
    int seats;
    String Grade;
    int rating;
    
                     


       

    /**
     * Creates new form NewJPanel
     */
    public professorcview(JPanel userProcessContainer, ProfessorHistory history, ProfessorHistory coursehistory, ProfessorHistory regcoursehistory,  ProfessorHistory sugg,String Subject, String pre_requisite, String Department, String Subject_code, String CRN, String professor_name, String Term_offered, String startDateTime, String endDateTime, String Description, int Credits, String status, int seats, String mode, String Grade, int rating) {
         this.userProcessContainer = userProcessContainer;
        initComponents();
        this.history = history;
        this.coursehistory = coursehistory;
        this.regcoursehistory = regcoursehistory;
        this.sugg = sugg;
     this.CRN = CRN;
     this.Subject_code = Subject_code;
    this. Term_offered = Term_offered;
     this.professor_name = professor_name;
    this.Subject = Subject;
    this.pre_requisite = pre_requisite;
    this.Department = Department;
    this. startDateTime = startDateTime;
    this.endDateTime = endDateTime;
    this.Description = Description;
    this.Credits=Credits;
    this.status = status;
    this.mode = mode;
    this.seats = seats;
    this.Grade = Grade;
    this.rating = rating;
     populatefieldc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
   
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        CourseDisc = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Namelbl = new javax.swing.JLabel();
        deplbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        termlbl = new javax.swing.JLabel();
        Specality = new javax.swing.JLabel();
        txtemailc = new javax.swing.JTextField();
        txtexpc = new javax.swing.JTextField();
        txtdepartmenthc = new javax.swing.JTextField();
        txtnamec = new javax.swing.JTextField();
        txtneuc = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnsearchcourse = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btnfeedback = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        btncoursesuggestion = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 153, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton7.setText("Register");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        CourseDisc.setEditable(false);
        CourseDisc.setColumns(20);
        CourseDisc.setRows(5);
        CourseDisc.setAutoscrolls(false);
        jScrollPane2.setViewportView(CourseDisc);

        jLabel1.setText("Course Description");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jButton7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(254, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jButton7)
                .addGap(85, 85, 85))
        );

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 3, true));

        Namelbl.setText("Name");

        deplbl.setText("NEU ID");

        jLabel7.setText("Experience");

        termlbl.setText("Email ID");

        Specality.setText("Department");

        txtneuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtneucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deplbl)
                            .addComponent(Namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(termlbl)
                            .addComponent(Specality))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtemailc, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(txtexpc)
                            .addComponent(txtdepartmenthc)
                            .addComponent(txtnamec)
                            .addComponent(txtneuc, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Namelbl)
                    .addComponent(txtnamec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deplbl)
                    .addComponent(txtneuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtexpc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(termlbl)
                    .addComponent(txtemailc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Specality)
                    .addComponent(txtdepartmenthc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btnsearchcourse.setText("Search Course");
        btnsearchcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchcourseActionPerformed(evt);
            }
        });

        btnsearch.setText("Settings");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        btnfeedback.setText("Feedback");
        btnfeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfeedbackActionPerformed(evt);
            }
        });

        btnhome.setText("Home");
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });

        btncoursesuggestion.setText("Course suggestion");
        btncoursesuggestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncoursesuggestionActionPerformed(evt);
            }
        });

        jButton8.setText("transcript");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnsearchcourse)
                            .addComponent(btnsearch)
                            .addComponent(btnfeedback)
                            .addComponent(btnhome, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncoursesuggestion)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(btnhome)
                .addGap(44, 44, 44)
                .addComponent(btnsearchcourse)
                .addGap(58, 58, 58)
                .addComponent(btnsearch)
                .addGap(53, 53, 53)
                .addComponent(btnfeedback)
                .addGap(42, 42, 42)
                .addComponent(btncoursesuggestion)
                .addGap(113, 113, 113)
                .addComponent(jButton8)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
   boolean shouldAddNewCourse = true;
    int totalCredits = 0;
    int p = 0;
    

    SimpleDateFormat dateTimeFormat = new SimpleDateFormat("MM/dd/yyyy HH:mm");
    try {
        Date Sdtm1 = dateTimeFormat.parse(startDateTime);
        Date edtm1 = dateTimeFormat.parse(endDateTime);
         System.out.println(edtm1);
        for (Professor.registercours regCourse : regcoursehistory.getRegcoursehistory()) {
            if (regCourse.getNEUID().equals("NEU010")) {
                p=1;
                for (Courses.CourseDetails course : regCourse.getCoursehistory()) {
                    Date newStartDate = dateTimeFormat.parse(course.getStartDateTime());
                    Date newEndDate = dateTimeFormat.parse(course.getEndDateTime());
                    if(course.getCourse_status().equals("ongoing"))
                        totalCredits += course.getCourse_credit();
                    // Check for date overlap
                    if (Sdtm1.before(newEndDate) && edtm1.after(newStartDate) && course.getCoursename().equals(Subject)) {
                   //     printCourseHistory();
                       shouldAddNewCourse = false;
                       JOptionPane.showMessageDialog(null, "Unable to register, There is a time conflict with your registered course or you have already completed or registered for the course", "Warning", JOptionPane.WARNING_MESSAGE);

                        break;
                    }
                    else if(totalCredits > 4 && seats == 0)
                    {
                    //    printCourseHistory();
                        JOptionPane.showMessageDialog(null, "Unable to register, there is are no seats available or you exceeding the required credits ", "Warning", JOptionPane.WARNING_MESSAGE);

                     
                        break;
                    }
                }
               
            }
        }
        
        if (shouldAddNewCourse && totalCredits <= 4 && seats > 0 )
        {
         //   printCourseHistory();
            addnewcourse();
            for (Courses.CourseDetails course : coursehistory.getCoursehistory()) {
                if(course.getCoursename().equals(Subject) && course.getEndDateTime().equals(endDateTime) && course.getStartDateTime().equals(startDateTime) && course.getCourse_professor_name().equals(professor_name))
                {
                 course.setCourse_seats(seats -1);
                }
            
        }

        }
        
        if(p==0)
        {
              Professor.registercours user1 = new Professor.registercours("Dev ", "NEU01","ongoing");
              
             Courses.CourseDetails vs = coursehistory.addNewcourse(); // addNewregcourse(Subject, pre_requisite, Department, Subject_code, CRN, professor_name, Term_offered, startDateTime, endDateTime, Description, Credits, status, seats, mode,  Grade);
            vs.setCRN(CRN);
            vs.setCourse_credit(Credits);
            vs.setCourse_department(Department);
            vs.setCourse_description(Description);
            vs.setEndDateTime(endDateTime);
            vs.setCourse_Type(mode);
            vs.setCourse_grade("NA");
            vs.setCourse_prerequisite(pre_requisite);
            vs.setCourse_professor_name(professor_name);
            vs.setCourse_seats(seats);
            vs.setStartDateTime(startDateTime);
            vs.setCourse_status("ongoing");
            vs.setCourse_code(Subject_code);
            vs.setTerm_offered(Term_offered);
            vs.setCoursename(Subject);
            vs.setRating(rating);
            user1.addCourse(vs);
            regcoursehistory.addruser(user1);

    }
        }
        
        
        
        
    
    catch (ParseException e) {
        // Handle the ParseException (e.g., log the error or throw a custom exception)
        System.err.println("Error parsing date: " + e.getMessage());
        // You might want to throw an exception here or handle it according to your application's logic
    }
    }
    
    
    public void addnewcourse(){        
                    
        for (Professor.registercours regCourse : regcoursehistory.getRegcoursehistory()) {
        if (regCourse.getNEUID().equals("NEU01")) {
            
            Courses.CourseDetails vs = coursehistory.addNewcourse(); // addNewregcourse(Subject, pre_requisite, Department, Subject_code, CRN, professor_name, Term_offered, startDateTime, endDateTime, Description, Credits, status, seats, mode,  Grade);
            vs.setCRN(CRN);
             vs.setCourse_credit(Credits);
            vs.setCourse_department(Department);
            vs.setCourse_description(Description);
            vs.setEndDateTime(endDateTime);
            vs.setCourse_Type(mode);
            vs.setCourse_grade("NA");
            vs.setCourse_prerequisite(pre_requisite);
            vs.setCourse_professor_name(professor_name);
            vs.setCourse_seats(seats);
            vs.setStartDateTime(startDateTime);
            vs.setCourse_status("ongoing");
            vs.setCourse_code(Subject_code);
            vs.setTerm_offered(Term_offered);
            vs.setCoursename(Subject);
            vs.setRating(rating);
            regCourse.addCourse(vs);
            
        }}
                    
                    
     /*       for (registercours regCourse : regcoursehistory.getRegcoursehistory()) {
            if (regCourse.getNEUID().equals("NEU01")) {
                for (Courses course : regCourse.getCoursehistory()) {
                      System.out.println(course.getsubject());
                                            System.out.println(course.getStatus());

                      
                }
            }
                }   */

            
        }
     

  private void populatefieldc(){
              
for (Professor.ProfessorProfile stu : pt.getHistory()) 
{
        if (stu.getNEUID().equals(Subject))
        {
            txtnamec.setText(stu.getName());
            txtdepartmenthc.setText(stu.getSpecalization());
            txtexpc.setText(stu.getNEUID());
          //  txtgradh.setText(stu.getGradyear());
            txtemailc.setText(String.valueOf(stu.getPhoneno()));
            txtneuc.setText(stu.getEmail_Id());
            
        }
        
        
}

for (Courses.CourseDetails ctu : coursehistory.getCoursehistory()) 
{
        if (ctu.getCoursename().equals(Subject))
        {
                CourseDisc.setText(Description);

     }
}
  }
    
    
    
 /*
    
    public void printCourseHistory() {
        for (registercours regCourse : regcoursehistory.getRegcoursehistory()) {
            System.out.println("Name: " + regCourse.getName());
            System.out.println("NEUID: " + regCourse.getNEUID());
            System.out.println("Course History:");
            
            // Iterate through coursehistory ArrayList and print course details
            for (Courses course : regCourse.getCoursehistory()) {
                System.out.println("  Course Code: " + course.getProfessor_name());
                System.out.println("  Course Name: " + course.getsubject());
                // Print other course details as needed
            }
            
            System.out.println("------------------------");
        }
    
    
   
    


    
        
    }//GEN-LAST:event_jButton7ActionPerformed
*/
    private void txtneucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtneucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtneucActionPerformed

    private void btnsearchcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchcourseActionPerformed
        // TODO add your handling code here:

        CoursesearchPanel panel = new CoursesearchPanel(userProcessContainer,  history,  coursehistory,  regcoursehistory,sugg );
        userProcessContainer.add("CoursesearchPanel", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnsearchcourseActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:

        UpdateAccountJPanel panel = new UpdateAccountJPanel(userProcessContainer,  history,  coursehistory,  regcoursehistory,sugg);
        userProcessContainer.add("UpdateAccountJPanel", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnfeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfeedbackActionPerformed
        // TODO add your handling code here:
        Rating panel = new Rating(userProcessContainer, history,  coursehistory, regcoursehistory,sugg);
        userProcessContainer.add("Rating", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnfeedbackActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        // TODO add your handling code here:

        Studenth panel = new Studenth(userProcessContainer, history,  coursehistory,  regcoursehistory,sugg);
        userProcessContainer.add("Studenth", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btncoursesuggestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncoursesuggestionActionPerformed
        // TODO add your handling code here:
        suggestion panel = new suggestion(userProcessContainer, history,  coursehistory, regcoursehistory,sugg);
        userProcessContainer.add("suggestion", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btncoursesuggestionActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        test panel = new test(userProcessContainer, history,  coursehistory, regcoursehistory,sugg);
        userProcessContainer.add("test", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton8ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea CourseDisc;
    private javax.swing.JLabel Namelbl;
    private javax.swing.JLabel Specality;
    private javax.swing.JButton btncoursesuggestion;
    private javax.swing.JButton btnfeedback;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnsearchcourse;
    private javax.swing.JLabel deplbl;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel termlbl;
    private javax.swing.JTextField txtdepartmenthc;
    private javax.swing.JTextField txtemailc;
    private javax.swing.JTextField txtexpc;
    private javax.swing.JTextField txtnamec;
    private javax.swing.JTextField txtneuc;
    // End of variables declaration//GEN-END:variables
}
