/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface;;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Courses.CourseDetails;
import java.awt.CardLayout;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Employer.EmployerHistory;
import Professor.ProfessorHistory;
import Student.Studentde;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.text.SimpleDateFormat;


/**
 *
 * @author Aneesh
 */
public class Rating extends javax.swing.JPanel {
   private JPanel userProcessContainer;
     Professor.ProfessorHistory history;
         Professor.ProfessorHistory coursehistory;
         Professor.ProfessorHistory regcoursehistory;
          Professor.ProfessorHistory sugg;
          Professor.ProfessorHistory ph;

          String p_neuid;
         String Subject1;
        String  proff;
        String   std;
        
       

    /**
     * Creates new form Rating
     */
    public Rating(JPanel userProcessContainer, ProfessorHistory history, ProfessorHistory ph, String p_neuid, ProfessorHistory coursehistory, ProfessorHistory regcoursehistory,  ProfessorHistory sugg) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        initComponents();
        this.ph =ph;
        this.p_neuid= p_neuid;
        this.history = history;
        this.coursehistory = coursehistory;
        this.regcoursehistory = regcoursehistory;
        this.sugg = sugg;
        populateTable2();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
     private void populateTable2(){
       
       for (Professor.registercours regCourse : regcoursehistory.getRegcoursehistory()) {
        if (regCourse.getNEUID().equals(p_neuid)) {
        DefaultTableModel dtm = (DefaultTableModel) tblstudentscompleted.getModel();
                dtm.setRowCount(0);        

        for(Courses.CourseDetails course: regCourse.getCoursehistory()){
            if(course.getCourse_status().equals("completed"))
           {
            Object[] row = new Object[7];
            row[0] = course;
            row[1] = course.getCourse_professor_name();
            row[2] = course.getCoursename();
            row[3] = course.getCourse_grade();
            row[4] = course.getTerm_offered();
            row[5] = course.getCourse_code();
            row[6] = course.getRating();
           

            
            dtm.addRow(row);
            
        }
        }
   }
       }
   }
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Suggesttxt = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblstudentscompleted = new javax.swing.JTable();
        btnselect = new javax.swing.JButton();
        bnsave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Strongly Agree", "Satisfied", "Disagree", "Strongly Disagree" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 196, 35));

        jLabel2.setText("The professor effectively communicated the course objectives and expectations.");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 377, 503, 35));

        jLabel3.setText("The professor demonstrated a deep knowledge of the subject matter");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 432, 503, 35));

        jLabel4.setText("The professor was accessible and approachable for questions and assistance");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 483, 503, 29));

        jLabel5.setText("The professor gave timely and constructive feedback on assignments and exams");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 529, 503, 28));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Strongly Agree", "Satisfied", "Disagree", "Strongly Disagree" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, 196, 35));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Strongly Agree", "Satisfied", "Disagree", "Strongly Disagree" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, 196, 32));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Strongly Agree", "Satisfied", "Disagree", "Strongly Disagree" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, 196, 36));

        Suggesttxt.setColumns(20);
        Suggesttxt.setRows(5);
        jScrollPane1.setViewportView(Suggesttxt);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 574, 663, 147));

        tblstudentscompleted.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Department", "Professor name", "Subject", "Grade", "Term offered", "Subject code", "Rating"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblstudentscompleted);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 93, 695, 210));

        btnselect.setText("Select");
        btnselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselectActionPerformed(evt);
            }
        });
        add(btnselect, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 90, 30));

        bnsave.setText("Save");
        bnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnsaveActionPerformed(evt);
            }
        });
        add(bnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 739, 100, 32));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Professor Rating");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 6, 839, 69));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jButton2.setText("Search Course");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Settings");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Feedback");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton8.setText("Course suggestion");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton8)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void btnselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselectActionPerformed
        // TODO add your handling code here:
        
         int selectedRow = tblstudentscompleted.getSelectedRow();
        if(selectedRow < 0){
              JOptionPane.showMessageDialog(null, "Please select a row from table to view details", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
         DefaultTableModel model = (DefaultTableModel) tblstudentscompleted.getModel();
            Courses.CourseDetails selectedcourse = (Courses.CourseDetails) model.getValueAt(selectedRow, 0);
           Subject1 = selectedcourse.getCoursename();
           proff = selectedcourse.getCourse_professor_name();
             std = selectedcourse.getStartDateTime();
        }
    }//GEN-LAST:event_btnselectActionPerformed

    private void bnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnsaveActionPerformed
        // TODO add your handling code here:
        
        
        
        
        String Department =  (String) jComboBox1.getSelectedItem();
       System.out.println(Department);
        
         String q1 =  (String) jComboBox2.getSelectedItem();
        
         String q2 =  (String) jComboBox1.getSelectedItem();
         
           
         String q3 =  (String) jComboBox3.getSelectedItem();
         
        String q4 =  (String) jComboBox4.getSelectedItem();


        preformfun(q1,q2,q3,q4);
        
        
         
        
    }//GEN-LAST:event_bnsaveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        CoursesearchPanel panel = new CoursesearchPanel(userProcessContainer,  history,  ph, p_neuid,coursehistory,  regcoursehistory, sugg);
        userProcessContainer.add("CoursesearchPanel", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        UpdateAccountJPanel panel = new UpdateAccountJPanel(userProcessContainer,  history,ph,p_neuid,coursehistory,  regcoursehistory,sugg);
        userProcessContainer.add("UpdateAccountJPanel", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          Rating panel = new Rating(userProcessContainer,  history,ph,p_neuid,coursehistory,  regcoursehistory,sugg);
        userProcessContainer.add("Rating", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        Studenth panel = new Studenth(userProcessContainer, history, ph, p_neuid,coursehistory,  regcoursehistory, sugg);
        userProcessContainer.add("Studenth", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         suggestion panel = new suggestion(userProcessContainer,  history,ph,p_neuid,coursehistory,  regcoursehistory,sugg);
        userProcessContainer.add("suggestion", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton8ActionPerformed

            private void preformfun(String q1, String q2,String q3, String q4){
                
     for (Courses.CourseDetails course : coursehistory.getCoursehistory()) {
    if (course.getCoursename()!= null && course.getCourse_professor_name() != null && course.getStartDateTime() != null
            && course.getCoursename().equals(Subject1) && course.getCourse_professor_name().equals(proff)
            && course.getStartDateTime().equals(std)) {
        int rating1 = calculateRating(q1);
        int rating2 = calculateRating(q2);
        int rating3 = calculateRating(q3);
        int rating4 = calculateRating(q4);

        // Update the course rating based on user responses
        int totalRating = (rating1 + rating2 + rating3 + rating4) / 4;
        course.setRating(totalRating);
    }

                /*
        for(Courses course: coursehistory.getCoursehistory()){
            if(course.getsubject().equals(Subject1) && course.getProfessor_name().equals(proff) && course.getStartDateTime().equals(std))
            {
                if(q1.equals("Strongly Agree"))
                {
                    course.setRating((course.getRating()+ 4)/2);
                }
                if(q1.equals("Satisfied"))
                {
                    course.setRating((course.getRating()+ 3)/2);
                }
                if(q1.equals("Disagree"))
                {
                    course.setRating((course.getRating()+ 2)/2);
                }
                if(q1.equals("Strongly Disagree"))
                {
                    course.setRating((course.getRating()+ 1)/2);
                }
                 if(q2.equals("Strongly Agree"))
                {
                    course.setRating((course.getRating()+ 4)/2);
                }
                if(q2.equals("Satisfied"))
                {
                    course.setRating((course.getRating()+ 3)/2);
                }
                if(q2.equals("Disagree"))
                {
                    course.setRating((course.getRating()+ 2)/2);
                }
                if(q2.equals("Strongly Disagree"))
                {
                    course.setRating((course.getRating()+ 1)/2);
                }
                 if(q3.equals("Strongly Agree"))
                {
                    course.setRating((course.getRating()+ 4)/2);
                }
                if(q3.equals("Satisfied"))
                {
                    course.setRating((course.getRating()+ 3)/2);
                }
                if(q3.equals("Disagree"))
                {
                    course.setRating((course.getRating()+ 2)/2);
                }
                if(q3.equals("Strongly Disagree"))
                {
                    course.setRating((course.getRating()+ 1)/2);
                }
                
                if(q4.equals("Strongly Agree"))
                {
                    course.setRating((course.getRating()+ 4)/2);
                }
                if(q4.equals("Satisfied"))
                {
                    course.setRating((course.getRating()+ 3)/2);
                }
                if(q4.equals("Disagree"))
                {
                    course.setRating((course.getRating()+ 2)/2);
                }
                if(q4.equals("Strongly Disagree"))
                {
                    course.setRating((course.getRating()+ 1)/2);
                }
            }
            }
            }
            
*/
     }
            }

    private int calculateRating(String response) {
    if (response.equals("Strongly Agree")) {
        return 4;
    } else if (response.equals("Satisfied")) {
        return 3;
    } else if (response.equals("Disagree")) {
        return 2;
    } else if (response.equals("Strongly Disagree")) {
        return 1;
    } else {
        // Handle invalid response
        return 0;
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Suggesttxt;
    private javax.swing.JButton bnsave;
    private javax.swing.JButton btnselect;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblstudentscompleted;
    // End of variables declaration//GEN-END:variables
}
