/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface;;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Courses.CourseDetails;
import java.awt.CardLayout;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Employer.EmployerHistory;
import Professor.ProfessorHistory;
import Student.Studentde;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.text.SimpleDateFormat;
/**
 *
 * @author devmi
 */
public class UpdateAccountJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
     Professor.ProfessorHistory history;
         Professor.ProfessorHistory coursehistory;
         Professor.ProfessorHistory regcoursehistory;
          Professor.ProfessorHistory sugg;
          Professor.ProfessorHistory ph;
          String p_neuid;
    /**
     * Creates new form ViewAccountJPanel
     */
   

    UpdateAccountJPanel(JPanel userProcessContainer, ProfessorHistory history, ProfessorHistory ph, String p_neuid, ProfessorHistory coursehistory, ProfessorHistory regcoursehistory,  ProfessorHistory sugg) {
             initComponents();
this.userProcessContainer = userProcessContainer;
       this.history = history;
        this.coursehistory = coursehistory;
        this.regcoursehistory = regcoursehistory;
        this.sugg = sugg;
        this.p_neuid = p_neuid;
        this.ph = ph;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnupdate = new javax.swing.JButton();
        viewuserjpanel1 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        SSN3 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        Role = new javax.swing.JLabel();
        txt = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtphonenumber = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        txtdepartment = new javax.swing.JTextField();
        txtacceptedyear = new javax.swing.JTextField();
        txtgraduatedyear = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtcampus = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(153, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 650, 112, 52));

        viewuserjpanel1.setBackground(new java.awt.Color(153, 153, 153));
        viewuserjpanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setText(" Name");
        viewuserjpanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 105, -1));

        SSN3.setText("Phone Number");
        viewuserjpanel1.add(SSN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 105, 20));

        jLabel45.setText("Age");
        viewuserjpanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 105, -1));

        Role.setText("Email -Id");
        viewuserjpanel1.add(Role, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 105, -1));
        viewuserjpanel1.add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 289, -1));
        viewuserjpanel1.add(txtage, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 289, -1));

        txtphonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphonenumberActionPerformed(evt);
            }
        });
        viewuserjpanel1.add(txtphonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 289, -1));
        viewuserjpanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 289, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Personal Details");
        viewuserjpanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 760, 70));

        jLabel6.setText("Password");
        viewuserjpanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 70, -1));
        viewuserjpanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 290, -1));
        viewuserjpanel1.add(txtdepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 290, -1));
        viewuserjpanel1.add(txtacceptedyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 290, -1));
        viewuserjpanel1.add(txtgraduatedyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, 290, -1));

        jLabel8.setText("Department");
        viewuserjpanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 90, -1));

        jLabel9.setText("Accepted Year");
        viewuserjpanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 80, -1));

        jLabel10.setText("Expected Graduation Year");
        viewuserjpanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, -1, -1));

        jLabel13.setText("Campus");
        viewuserjpanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));
        viewuserjpanel1.add(txtcampus, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 290, -1));

        add(viewuserjpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 745, 611));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jButton2.setText("Search Course");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Settings");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Feedback");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton8.setText("Course suggestion");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton8)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));
    }// </editor-fold>//GEN-END:initComponents

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        for (Student.Studentde stu : history.getHistory()) 
{
        if (stu.getNEUID().equals(p_neuid))
        {
            stu.setName(txt.getText());
            stu.setSpecalization(txtdepartment.getText());
            stu.setAge(Integer.valueOf(txtage.getText()));
            stu.setAcceptedyear(txtacceptedyear.getText());
            stu.setEmail_Id(txtemail.getText());
            stu.setPhoneno(Integer.valueOf(txtphonenumber.getText()));
            stu.setCampus(txtcampus.getText());
            stu.setPassword(txtphonenumber.getText());
            
        }
            
        
        
        
}
        
    }//GEN-LAST:event_btnupdateActionPerformed

    private void txtphonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphonenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphonenumberActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        CoursesearchPanel panel = new CoursesearchPanel(userProcessContainer,  history,  ph, p_neuid,coursehistory,  regcoursehistory, sugg);
        userProcessContainer.add("CoursesearchPanel", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        UpdateAccountJPanel panel = new UpdateAccountJPanel(userProcessContainer,  history,ph,p_neuid,coursehistory,  regcoursehistory,sugg);
        userProcessContainer.add("UpdateAccountJPanel", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          Rating panel = new Rating(userProcessContainer,  history,ph,p_neuid,coursehistory,  regcoursehistory,sugg);
        userProcessContainer.add("Rating", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        Studenth panel = new Studenth(userProcessContainer, history, ph, p_neuid,coursehistory,  regcoursehistory, sugg);
        userProcessContainer.add("Studenth", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         suggestion panel = new suggestion(userProcessContainer,  history,ph,p_neuid,coursehistory,  regcoursehistory,sugg);
        userProcessContainer.add("suggestion", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Role;
    private javax.swing.JLabel SSN3;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt;
    private javax.swing.JTextField txtacceptedyear;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtcampus;
    private javax.swing.JTextField txtdepartment;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtgraduatedyear;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtphonenumber;
    private javax.swing.JPanel viewuserjpanel1;
    // End of variables declaration//GEN-END:variables
}
