/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Courses.CourseDetails;
import java.awt.CardLayout;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Employer.EmployerHistory;
import Professor.ProfessorHistory;
import Student.Studentde;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.text.SimpleDateFormat;
/**
 *
 * @author devmi
 */
public class UpdateAccountJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
     Professor.ProfessorHistory history;
         Professor.ProfessorHistory coursehistory;
         Professor.ProfessorHistory regcoursehistory;
          Professor.ProfessorHistory sugg;
    /**
     * Creates new form ViewAccountJPanel
     */
   

    UpdateAccountJPanel(JPanel userProcessContainer, ProfessorHistory history, ProfessorHistory coursehistory, ProfessorHistory regcoursehistory,  ProfessorHistory sugg) {
             initComponents();
this.userProcessContainer = userProcessContainer;
       this.history = history;
        this.coursehistory = coursehistory;
        this.regcoursehistory = regcoursehistory;
        this.sugg = sugg;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnupdate = new javax.swing.JButton();
        viewuserjpanel1 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        SSN3 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        Role = new javax.swing.JLabel();
        txt = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtphonenumber = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        txtdepartment = new javax.swing.JTextField();
        txtacceptedyear = new javax.swing.JTextField();
        txtgraduatedyear = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtcampus = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnsearchcourse = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btnfeedback = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        btncoursesuggestion = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(240, 175, 109));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 695, 112, 52));

        viewuserjpanel1.setBackground(new java.awt.Color(211, 242, 242));
        viewuserjpanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setText(" Name");
        viewuserjpanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 105, -1));

        SSN3.setText("Phone Number");
        viewuserjpanel1.add(SSN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 105, 20));

        jLabel45.setText("Age");
        viewuserjpanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 105, -1));

        Role.setText("Email -Id");
        viewuserjpanel1.add(Role, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 105, -1));
        viewuserjpanel1.add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 289, -1));
        viewuserjpanel1.add(txtage, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 289, -1));

        txtphonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphonenumberActionPerformed(evt);
            }
        });
        viewuserjpanel1.add(txtphonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 289, -1));
        viewuserjpanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 289, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Personal Details");
        viewuserjpanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 30, 760, 70));

        jLabel6.setText("Password");
        viewuserjpanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 60, -1));
        viewuserjpanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 290, -1));
        viewuserjpanel1.add(txtdepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 290, -1));
        viewuserjpanel1.add(txtacceptedyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 290, -1));
        viewuserjpanel1.add(txtgraduatedyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, 290, -1));

        jLabel8.setText("Department");
        viewuserjpanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 60, -1));

        jLabel9.setText("Accepted Year");
        viewuserjpanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 80, -1));

        jLabel10.setText("Expected Graduation Year");
        viewuserjpanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, -1, -1));

        jLabel13.setText("Campus");
        viewuserjpanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));
        viewuserjpanel1.add(txtcampus, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 290, -1));

        add(viewuserjpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 35, 745, 611));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btnsearchcourse.setText("Search Course");
        btnsearchcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchcourseActionPerformed(evt);
            }
        });

        btnsearch.setText("Settings");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        btnfeedback.setText("Feedback");
        btnfeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfeedbackActionPerformed(evt);
            }
        });

        btnhome.setText("Home");
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });

        btncoursesuggestion.setText("Course suggestion");
        btncoursesuggestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncoursesuggestionActionPerformed(evt);
            }
        });

        jButton8.setText("transcript");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnsearchcourse)
                            .addComponent(btnsearch)
                            .addComponent(btnfeedback)
                            .addComponent(btnhome, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncoursesuggestion)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(btnhome)
                .addGap(44, 44, 44)
                .addComponent(btnsearchcourse)
                .addGap(58, 58, 58)
                .addComponent(btnsearch)
                .addGap(53, 53, 53)
                .addComponent(btnfeedback)
                .addGap(42, 42, 42)
                .addComponent(btncoursesuggestion)
                .addGap(113, 113, 113)
                .addComponent(jButton8)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 35, 110, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnupdateActionPerformed

    private void txtphonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphonenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphonenumberActionPerformed

    private void btnsearchcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchcourseActionPerformed
        // TODO add your handling code here:

        CoursesearchPanel panel = new CoursesearchPanel(userProcessContainer,  history,  coursehistory,  regcoursehistory,sugg );
        userProcessContainer.add("CoursesearchPanel", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnsearchcourseActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:

        UpdateAccountJPanel panel = new UpdateAccountJPanel(userProcessContainer,  history,  coursehistory,  regcoursehistory, sugg);
        userProcessContainer.add("UpdateAccountJPanel", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnfeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfeedbackActionPerformed
        // TODO add your handling code here:
        Rating panel = new Rating(userProcessContainer, history,  coursehistory, regcoursehistory,sugg);
        userProcessContainer.add("Rating", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnfeedbackActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        // TODO add your handling code here:

        Studenth panel = new Studenth(userProcessContainer, history,  coursehistory,  regcoursehistory,sugg);
        userProcessContainer.add("Studenth", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btncoursesuggestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncoursesuggestionActionPerformed
        // TODO add your handling code here:
        suggestion panel = new suggestion(userProcessContainer, history,  coursehistory,  regcoursehistory,sugg);
        userProcessContainer.add("suggestion", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btncoursesuggestionActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        test panel = new test(userProcessContainer, history,  coursehistory, regcoursehistory,sugg);
        userProcessContainer.add("test", panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Role;
    private javax.swing.JLabel SSN3;
    private javax.swing.JButton btncoursesuggestion;
    private javax.swing.JButton btnfeedback;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnsearchcourse;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt;
    private javax.swing.JTextField txtacceptedyear;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtcampus;
    private javax.swing.JTextField txtdepartment;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtgraduatedyear;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtphonenumber;
    private javax.swing.JPanel viewuserjpanel1;
    // End of variables declaration//GEN-END:variables
}
